// ─── CONSEILS DU JOUR ───────────────────────────────────────────────────────
export const CONSEILS = {
  homme: [
    {
      id: 'h1',
      texte: "Le Prophète ﷺ était le meilleur avec sa famille. Aujourd'hui, dis à ta femme une chose que tu apprécies chez elle.",
      texteEN: "The Prophet ﷺ was the best to his family. Today, tell your wife one thing you appreciate about her.",
      source: "Tirmidhi",
      psycho: "Les expressions de gratitude renforcent le lien affectif et augmentent la satisfaction conjugale.",
      psychoEN: "Expressions of gratitude strengthen the emotional bond and increase marital satisfaction.",
      icone: '💬',
    },
    {
      id: 'h2',
      texte: "Aide ta femme dans les tâches ménagères. Le Prophète ﷺ cousait lui-même ses vêtements et aidait à la maison.",
      texteEN: "Help your wife with household tasks. The Prophet ﷺ sewed his own clothes and helped around the house.",
      source: "Bukhari",
      psycho: "Le partage des responsabilités est l'un des principaux facteurs de bonheur conjugal.",
      psychoEN: "Sharing responsibilities is one of the main factors of marital happiness.",
      icone: '🏡',
    },
    {
      id: 'h3',
      texte: "Écoute ta femme vraiment. Pose ton téléphone, regarde-la dans les yeux et écoute sans préparer ta réponse.",
      texteEN: "Truly listen to your wife. Put down your phone, look her in the eyes, and listen without preparing your response.",
      source: "Psychologie islamique",
      psycho: "L'écoute active est la compétence n°1 des couples épanouis selon les études.",
      psychoEN: "Active listening is the #1 skill of fulfilled couples according to studies.",
      icone: '👂',
    },
    {
      id: 'h4',
      texte: "Allah dit : 'Vivez avec elles de façon convenable.' (Coran 4:19). Demande-toi : est-ce que je vis avec elle de la meilleure façon ?",
      texteEN: "Allah says: 'Live with them in kindness.' (Quran 4:19). Ask yourself: am I living with her in the best way?",
      source: "Coran 4:19",
      psycho: "L'auto-évaluation régulière est un outil puissant de développement personnel.",
      psychoEN: "Regular self-assessment is a powerful tool for personal development.",
      icone: '📖',
    },
    {
      id: 'h5',
      texte: "Offre-lui un cadeau aujourd'hui, même petit. 'Offrez-vous des cadeaux, vous vous aimerez davantage.' (Hadith)",
      texteEN: "Give her a gift today, even a small one. 'Give gifts to one another, you will love each other more.' (Hadith)",
      source: "Al-Adab Al-Mufrad",
      psycho: "Les petits gestes intentionnels maintiennent la flamme dans une relation longue durée.",
      psychoEN: "Small intentional gestures maintain the flame in a long-term relationship.",
      icone: '🎁',
    },
    {
      id: 'h6',
      texte: "Protège ta femme de tout mal, y compris de tes propres colères. La force n'est pas de frapper, mais de se maîtriser.",
      texteEN: "Protect your wife from all harm, including your own anger. Strength is not striking but controlling oneself.",
      source: "Bukhari",
      psycho: "La régulation émotionnelle est le fondement d'une relation saine et sécurisante.",
      psychoEN: "Emotional regulation is the foundation of a healthy and secure relationship.",
      icone: '🛡️',
    },
    {
      id: 'h7',
      texte: "Fais une prière de 2 rakats avec ta femme ce soir. La famille qui prie ensemble crée un lien spirituel unique.",
      texteEN: "Pray 2 rakats with your wife this evening. A family that prays together creates a unique spiritual bond.",
      source: "Abu Dawud",
      psycho: "Le partage de rituels spirituels renforce profondément l'intimité émotionnelle.",
      psychoEN: "Sharing spiritual rituals deeply strengthens emotional intimacy.",
      icone: '🤲',
    },
    {
      id: 'h8',
      texte: "Rentre à l'heure ce soir et préviens-la si tu as du retard. Le Prophète ﷺ prévenait ses proches. La présence prévisible crée la sécurité.",
      texteEN: "Come home on time tonight and let her know if you'll be late. The Prophet ﷺ informed his family. Predictable presence creates security.",
      source: "Sunnah prophétique",
      psycho: "La fiabilité et la prévisibilité sont des fondements de la sécurité émotionnelle dans un couple.",
      psychoEN: "Reliability and predictability are foundations of emotional security in a couple.",
      icone: '🏠',
    },
    {
      id: 'h9',
      texte: "Dis à ta femme 'je t'aime' aujourd'hui. Le Prophète ﷺ a dit : 'Lorsque l'un de vous aime son frère, qu'il lui fasse savoir.' Cela s'applique d'abord à son épouse.",
      texteEN: "Tell your wife 'I love you' today. The Prophet ﷺ said: 'When one of you loves his brother, let him tell them.' This applies first to one's wife.",
      source: "Tirmidhi",
      psycho: "Exprimer verbalement son amour régulièrement maintient le lien affectif et renforce le sentiment d'être valorisé.",
      psychoEN: "Verbally expressing love regularly maintains the emotional bond and strengthens the feeling of being valued.",
      icone: '❤️',
    },
    {
      id: 'h10',
      texte: "Défends l'honneur de ta femme en son absence. Ne parle jamais d'elle en mal devant les autres. C'est une forme de trahison que l'Islam interdit.",
      texteEN: "Defend your wife's honor in her absence. Never speak ill of her in front of others. This is a betrayal that Islam forbids.",
      source: "Nasa'i",
      psycho: "Savoir que son conjoint nous défend en notre absence crée un sentiment de sécurité et de loyauté profondes.",
      psychoEN: "Knowing that your spouse defends you in your absence creates a profound feeling of security and loyalty.",
      icone: '🛡️',
    },
    {
      id: 'h11',
      texte: "Pose-lui la question ce soir : 'Comment tu vas vraiment ?' Pas juste par politesse — avec une vraie intention d'écouter.",
      texteEN: "Ask her this evening: 'How are you really?' Not just as a formality — with a genuine intention to listen.",
      source: "Psychologie du couple",
      psycho: "S'intéresser sincèrement au vécu intérieur de son épouse est l'un des actes les plus nourrissants pour une relation.",
      psychoEN: "Sincerely caring about your wife's inner life is one of the most nourishing acts for a relationship.",
      icone: '💭',
    },
    {
      id: 'h12',
      texte: "Contrôle ton regard aujourd'hui. Abaisser le regard est une obligation islamique qui protège le foyer et renforce la confiance mutuelle.",
      texteEN: "Guard your gaze today. Lowering the gaze is an Islamic obligation that protects the home and reinforces mutual trust.",
      source: "Coran 24:30",
      psycho: "La fidélité du regard renforce la confiance et réduit l'insécurité dans la relation conjugale.",
      psychoEN: "Faithfulness of the gaze strengthens trust and reduces insecurity in the marital relationship.",
      icone: '👁️',
    },
    {
      id: 'h13',
      texte: "Implique-la dans une décision du foyer aujourd'hui. Le Prophète ﷺ consultait ses épouses. La consultation renforce le sentiment d'appartenance.",
      texteEN: "Involve her in a household decision today. The Prophet ﷺ consulted his wives. Consultation strengthens the sense of belonging.",
      source: "Coran 42:38",
      psycho: "Être consulté dans les décisions augmente le sentiment d'importance et d'appartenance dans la relation.",
      psychoEN: "Being consulted in decisions increases the sense of importance and belonging in the relationship.",
      icone: '🤝',
    },
    {
      id: 'h14',
      texte: "Rappelle-lui un souvenir de vos débuts aujourd'hui. 'Tu te souviens quand...' Les souvenirs heureux partagés renforcent le sentiment d'appartenance commune.",
      texteEN: "Remind her of a memory from your early days today. 'Do you remember when...' Shared happy memories strengthen the sense of common belonging.",
      source: "Psychologie positive",
      psycho: "Revisiter les souvenirs positifs réactive les émotions fondatrices du couple et renforce le lien d'appartenance.",
      psychoEN: "Revisiting positive memories reactivates the founding emotions of the couple and strengthens the bond of belonging.",
      icone: '🌿',
    },
    {
      id: 'h15',
      texte: "Sois généreux envers ta famille aujourd'hui. Ramène quelque chose — un plat, un fruit, une surprise. 'Ce que tu dépenses pour ta famille est une sadaqa.'",
      texteEN: "Be generous to your family today. Bring something — a dish, a fruit, a surprise. 'What you spend for your family is a sadaqa.'",
      source: "Bukhari",
      psycho: "La générosité matérielle exprime le soin et la protection, deux besoins fondamentaux dans un couple.",
      psychoEN: "Material generosity expresses care and protection, two fundamental needs in a couple.",
      icone: '🎁',
    },
    {
      id: 'h16',
      texte: "Fais dua pour ta femme ce soir. Invoque Allah pour sa santé, son bonheur et sa foi. Celui qui prie pour son conjoint exprime un amour authentique.",
      texteEN: "Make dua for your wife this evening. Invoke Allah for her health, happiness, and faith. Praying for your spouse expresses authentic love.",
      source: "Tradition prophétique",
      psycho: "Prier pour son conjoint oriente l'attention vers ses besoins plutôt que les siennes, créant de l'empathie.",
      psychoEN: "Praying for your spouse redirects attention toward their needs rather than your own, creating empathy.",
      icone: '🤲',
    },
    {
      id: 'h17',
      texte: "Évite les comparaisons blessantes. Ne dis jamais 'la femme d'Untel fait ceci'. L'Islam interdit de rabaisser son conjoint. Valorise-la telle qu'elle est.",
      texteEN: "Avoid hurtful comparisons. Never say 'So-and-so's wife does this.' Islam forbids belittling your spouse. Value her as she is.",
      source: "Psychologie islamique",
      psycho: "Les comparaisons négatives sont l'un des comportements les plus destructeurs de l'estime de soi dans le couple.",
      psychoEN: "Negative comparisons are one of the most destructive behaviors for self-esteem in a couple.",
      icone: '🚫',
    },
    {
      id: 'h18',
      texte: "Partage avec elle quelque chose que tu as appris ou réfléchi aujourd'hui. La croissance intellectuelle partagée crée une complicité rare.",
      texteEN: "Share with her something you learned or reflected on today. Shared intellectual growth creates a rare complicity.",
      source: "Psychologie du couple",
      psycho: "L'intimité intellectuelle — partager ses pensées et réflexions — est un facteur clé de la satisfaction conjugale.",
      psychoEN: "Intellectual intimacy — sharing thoughts and reflections — is a key factor of marital satisfaction.",
      icone: '💡',
    },
    {
      id: 'h19',
      texte: "Demande-lui pardon pour quelque chose, même si c'est vieux. Le Prophète ﷺ était le premier à se réconcilier. Humilité ne veut pas dire faiblesse.",
      texteEN: "Ask her forgiveness for something, even if it's old. The Prophet ﷺ was the first to reconcile. Humility does not mean weakness.",
      source: "Sahih al-Bukhari 6077",
      psycho: "Demander pardon libère les deux parties d'un poids émotionnel et réinitialise la dynamique relationnelle.",
      psychoEN: "Asking for forgiveness frees both parties from an emotional burden and resets the relational dynamic.",
      icone: '🕊️',
    },
    {
      id: 'h20',
      texte: "Mange avec ta famille ce soir, assis ensemble, sans télévision. 'La barakah se trouve dans le repas partagé.' C'est une sunnah qui renforce la connexion.",
      texteEN: "Eat with your family tonight, sitting together, without television. 'Barakah is found in the shared meal.' This sunnah strengthens connection.",
      source: "Ibn Majah",
      psycho: "Les repas partagés sans écrans sont l'un des rituels les plus efficaces pour maintenir la connexion familiale.",
      psychoEN: "Shared meals without screens are one of the most effective rituals for maintaining family connection.",
      icone: '🍽️',
    },
    {
      id: 'h21',
      texte: "Prends soin de ton apparence pour ta femme. Le Prophète ﷺ se parfumait et soignait sa présentation. Le soin de soi est un acte d'amour envers son conjoint.",
      texteEN: "Take care of your appearance for your wife. The Prophet ﷺ wore perfume and attended to his presentation. Self-care is an act of love toward your spouse.",
      source: "Sahih al-Bukhari 5923",
      psycho: "Prendre soin de son apparence pour son conjoint signale l'effort et l'attention, deux facteurs de satisfaction conjugale.",
      psychoEN: "Taking care of your appearance for your spouse signals effort and attention, two factors of marital satisfaction.",
      icone: '✨',
    },
    {
      id: 'h22',
      texte: "Fixe une sortie pour vous deux cette semaine. Une promenade, un café. Créer des moments exclusifs au couple nourrit l'intimité mieux que les grands événements rares.",
      texteEN: "Plan an outing for the two of you this week. A walk, a coffee. Creating exclusive couple moments nourishes intimacy better than rare grand events.",
      source: "Psychologie du couple",
      psycho: "Les sorties régulières en couple créent de nouvelles expériences partagées qui maintiennent la vitalité de la relation.",
      psychoEN: "Regular couple outings create new shared experiences that maintain the vitality of the relationship.",
      icone: '🌙',
    },
    {
      id: 'h23',
      texte: "Aujourd'hui, ne critique pas — même intérieurement. L'Islam enseigne de penser du bien de son conjoint. Cherche activement ses qualités.",
      texteEN: "Today, don't criticize — even inwardly. Islam teaches thinking well of your spouse. Actively seek her qualities.",
      source: "Psychologie positive",
      psycho: "Orienter son attention vers les qualités de l'autre plutôt que ses défauts change profondément la dynamique conjugale.",
      psychoEN: "Intentionally directing attention toward the other's qualities rather than their faults profoundly changes the marital dynamic.",
      icone: '🌱',
    },
    {
      id: 'h24',
      texte: "Mets ton téléphone de côté pendant le dîner ce soir. Être présent physiquement ne suffit pas — la présence totale est un cadeau que peu d'hommes offrent.",
      texteEN: "Put your phone away during dinner tonight. Being physically present is not enough — total presence is a gift few men offer.",
      source: "Psychologie du couple",
      psycho: "L'attention totale accordée à son conjoint lors des repas est l'un des actes les plus impactants pour la connexion quotidienne.",
      psychoEN: "Complete attention given to your spouse during meals is one of the most impactful acts for daily connection.",
      icone: '📵',
    },
    {
      id: 'h25',
      texte: "Demande à ta femme ce qu'elle ressent — pas ce qu'elle pense. Les femmes ont besoin d'être comprises émotionnellement avant d'être conseillées.",
      texteEN: "Ask your wife what she feels — not what she thinks. Women need to be understood emotionally before being advised.",
      source: "Psychologie des émotions",
      psycho: "Distinguer la question émotionnelle de la question pratique est une compétence clé de l'intelligence relationnelle.",
      psychoEN: "Distinguishing the emotional question from the practical one is a key skill of relational intelligence.",
      icone: '💝',
    },
    {
      id: 'h26',
      texte: "Fais quelque chose que ta femme t'a demandé de faire depuis longtemps. Honorer ses demandes montre que tu l'as vraiment écoutée.",
      texteEN: "Do something your wife has asked you to do for a long time. Honoring her requests shows you truly listened.",
      source: "Psychologie du couple",
      psycho: "Répondre à une demande ancienne montre que les paroles de son conjoint comptent, réduisant le sentiment d'être ignoré.",
      psychoEN: "Responding to an old request shows that your spouse's words matter, reducing the feeling of being ignored.",
      icone: '✅',
    },
    {
      id: 'h27',
      texte: "Invoque Allah ce soir pour la stabilité de votre foyer. 'Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin.' C'est la dua du couple parfait.",
      texteEN: "Invoke Allah this evening for the stability of your home. 'Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin.' This is the dua of the perfect couple.",
      source: "Coran 25:74",
      psycho: "La prière d'intention pour son couple renforce l'engagement personnel envers la relation et crée un sens commun.",
      psychoEN: "Prayerfully intending for one's couple strengthens personal commitment to the relationship and creates shared meaning.",
      icone: '🌙',
    },
    {
      id: 'h28',
      texte: "Sois patient avec ses défauts aujourd'hui. 'Si vous les avez en aversion, il se peut qu'Allah ait placé beaucoup de bien en elles.' La patience est une ibada.",
      texteEN: "Be patient with her faults today. 'If you dislike them, perhaps Allah has placed much good in them.' Patience is an ibada.",
      source: "Coran 4:19",
      psycho: "L'acceptation inconditionnelle des défauts de l'autre est le fondement le plus solide d'un amour durable.",
      psychoEN: "Unconditional acceptance of the other's faults is the most solid foundation of lasting love.",
      icone: '🌱',
    },
    {
      id: 'h29',
      texte: "Parle à ta femme de tes rêves pour votre famille. Les couples qui partagent une vision commune avancent dans la même direction et résistent mieux aux épreuves.",
      texteEN: "Tell your wife about your dreams for your family. Couples who share a common vision move in the same direction and better resist hardships.",
      source: "Psychologie du couple",
      psycho: "Avoir une vision commune du futur conjugal et familial est l'un des prédicteurs les plus solides de la stabilité d'un couple.",
      psychoEN: "Having a shared vision of the couple's and family's future is one of the strongest predictors of a couple's stability.",
      icone: '🌟',
    },
    {
      id: 'h30',
      texte: "Termine la journée en disant à ta femme une chose positive sur comment elle a été aujourd'hui. Finir la journée sur une note bienveillante conditionne le lendemain.",
      texteEN: "End the day by telling your wife one positive thing about how she was today. Ending the day on a kind note conditions tomorrow.",
      source: "Psychologie positive",
      psycho: "Les interactions positives de fin de journée ont un effet neurologique de consolidation — elles conditionnent la qualité du lien au réveil.",
      psychoEN: "Positive end-of-day interactions have a neurological consolidation effect — they condition the quality of the bond upon waking.",
      icone: '🌅',
    },
  ],
  femme: [
    {
      id: 'f1',
      texte: "La femme qui accueille son mari avec un sourire sincère pratique un acte d'ibada. Souris-lui aujourd'hui dès qu'il rentre.",
      texteEN: "A woman who welcomes her husband with a sincere smile practices an act of ibada. Smile at him today when he comes home.",
      source: "Sagesse islamique",
      psycho: "Un accueil chaleureux régule le stress du retour à la maison et renforce la connexion.",
      psychoEN: "A warm welcome regulates the stress of coming home and strengthens connection.",
      icone: '😊',
    },
    {
      id: 'f2',
      texte: "'La meilleure femme est celle qui, lorsque tu la regardes, te réjouit.' Prends soin de toi pour toi et pour votre couple.",
      texteEN: "'The best woman is the one who, when you look at her, brings you joy.' Take care of yourself for you and for your couple.",
      source: "Hadith",
      psycho: "Prendre soin de son apparence booste l'estime de soi et l'attractivité dans le couple.",
      psychoEN: "Taking care of one's appearance boosts self-esteem and attractiveness in the couple.",
      icone: '✨',
    },
    {
      id: 'f3',
      texte: "Dis à ton mari ce dont tu as besoin clairement et avec douceur. Il ne peut pas deviner tes besoins.",
      texteEN: "Tell your husband what you need clearly and gently. He cannot guess your needs.",
      source: "Psychologie islamique",
      psycho: "La communication directe et bienveillante est plus efficace que les attentes implicites.",
      psychoEN: "Direct and kind communication is more effective than implicit expectations.",
      icone: '💬',
    },
    {
      id: 'f4',
      texte: "Fais dua pour ton mari aujourd'hui. Invoque Allah pour qu'Il le guide et le bénisse dans ce qu'il entreprend.",
      texteEN: "Make dua for your husband today. Invoke Allah to guide him and bless him in what he undertakes.",
      source: "Tradition prophétique",
      psycho: "Prier pour son conjoint transforme le regard qu'on porte sur lui.",
      psychoEN: "Praying for your spouse transforms the way you look at them.",
      icone: '🤲',
    },
    {
      id: 'f5',
      texte: "Remercie ton mari pour quelque chose de concret aujourd'hui. La gratitude exprimée change la dynamique d'un couple.",
      texteEN: "Thank your husband for something concrete today. Expressed gratitude changes the dynamic of a couple.",
      source: "Hadith",
      psycho: "La gratitude est l'un des prédicteurs les plus solides de la satisfaction conjugale.",
      psychoEN: "Gratitude is one of the strongest predictors of marital satisfaction.",
      icone: '🙏',
    },
    {
      id: 'f6',
      texte: "Khadija (ra) était un soutien inconditionnel pour le Prophète ﷺ. Sois-tu aussi un pilier pour ton mari dans les moments difficiles.",
      texteEN: "Khadijah (ra) was an unconditional support for the Prophet ﷺ. Be a pillar for your husband in difficult times.",
      source: "Sahih al-Bukhari 3818",
      psycho: "Le soutien émotionnel inconditionnel crée un sentiment de sécurité profond.",
      psychoEN: "Unconditional emotional support creates a profound sense of security.",
      icone: '💪',
    },
    {
      id: 'f7',
      texte: "Prends du temps pour toi aujourd'hui. Une femme épanouie est une meilleure épouse, mère et personne.",
      texteEN: "Take some time for yourself today. A fulfilled woman is a better wife, mother, and person.",
      source: "Psychologie islamique",
      psycho: "Prendre soin de soi (self-care) prévient l'épuisement émotionnel dans la relation.",
      psychoEN: "Self-care prevents emotional exhaustion in the relationship.",
      icone: '🌸',
    },
    {
      id: 'f8',
      texte: "Exprime ta reconnaissance à ton mari pour ce qu'il fait pour le foyer, même si c'est son devoir. 'Celui qui ne remercie pas les gens ne remercie pas Allah.'",
      texteEN: "Express your appreciation to your husband for what he does for the home, even if it is his duty. 'Whoever does not thank people does not thank Allah.'",
      source: "Abu Dawud",
      psycho: "La gratitude exprimée régulièrement augmente la satisfaction des deux conjoints et renforce le comportement positif.",
      psychoEN: "Regularly expressed gratitude increases the satisfaction of both spouses and reinforces positive behavior.",
      icone: '🙏',
    },
    {
      id: 'f9',
      texte: "Crée une ambiance agréable à la maison aujourd'hui. Un espace propre, une odeur douce, une lumière chaleureuse. Le foyer doit être un refuge, pas une source de stress.",
      texteEN: "Create a pleasant atmosphere at home today. A clean space, a sweet scent, warm lighting. The home must be a refuge, not a source of stress.",
      source: "Sagesse islamique",
      psycho: "L'environnement physique du foyer influence directement le bien-être émotionnel de tous ses occupants.",
      psychoEN: "The physical environment of the home directly influences the emotional well-being of all its occupants.",
      icone: '🏡',
    },
    {
      id: 'f10',
      texte: "Dis à ton mari quelque chose que tu admires sincèrement chez lui. Pas un compliment général — quelque chose de précis et vrai.",
      texteEN: "Tell your husband something you sincerely admire about him. Not a general compliment — something precise and true.",
      source: "Psychologie positive",
      psycho: "Les compliments précis et sincères ont un impact bien plus profond que les généralités sur l'estime de soi.",
      psychoEN: "Precise and sincere compliments have a much deeper impact than generalities on self-esteem.",
      icone: '💬',
    },
    {
      id: 'f11',
      texte: "Évite de discuter d'un sujet lourd dès qu'il rentre du travail. Laisse-lui un moment de décompression. C'est de la sagesse, pas de la faiblesse.",
      texteEN: "Avoid discussing a heavy topic as soon as he comes home from work. Give him a moment to decompress. It's wisdom, not weakness.",
      source: "Psychologie du couple",
      psycho: "Respecter les besoins de décompression de son conjoint réduit les conflits liés à la fatigue et améliore la qualité des échanges.",
      psychoEN: "Respecting your spouse's decompression needs reduces conflict from fatigue and improves the quality of exchanges.",
      icone: '⏸️',
    },
    {
      id: 'f12',
      texte: "Partage avec lui un projet ou un rêve que tu as. Les couples qui se partagent leurs aspirations construisent une vision commune et restent plus soudés.",
      texteEN: "Share a project or dream you have with him. Couples who share their aspirations build a common vision and stay more united.",
      source: "Psychologie du couple",
      psycho: "Partager ses aspirations profondes crée de l'intimité et aligne les deux conjoints vers un futur commun.",
      psychoEN: "Sharing one's deep aspirations creates intimacy and aligns both spouses toward a common future.",
      icone: '🌟',
    },
    {
      id: 'f13',
      texte: "Contrôle ta parole aujourd'hui. 'La parole est un dépôt (amanah).' Avant de dire quelque chose, demande-toi : est-ce vrai, est-ce utile, est-ce bienveillant ?",
      texteEN: "Watch your words today. 'Speech is a trust (amanah).' Before saying something, ask yourself: is it true, is it useful, is it kind?",
      source: "Sagesse islamique",
      psycho: "Le filtre des paroles — vrai, utile, bienveillant — est une technique de communication non-violente validée par la psychologie.",
      psychoEN: "The filter of words — true, useful, kind — is a non-violent communication technique validated by psychology.",
      icone: '🗣️',
    },
    {
      id: 'f14',
      texte: "Aïcha (ra) était la meilleure amie du Prophète ﷺ. Sois aujourd'hui la meilleure amie de ton mari — quelqu'un à qui il peut tout dire.",
      texteEN: "Aisha (ra) was the Prophet's ﷺ best friend. Today, be your husband's best friend — someone he can tell everything to.",
      source: "Sahih al-Bukhari 5228",
      psycho: "L'amitié conjugale — se sentir ami(e) de son conjoint — est le prédicteur n°1 de la stabilité d'un couple selon Gottman.",
      psychoEN: "Marital friendship — feeling like friends with your spouse — is the #1 predictor of couple stability according to Gottman.",
      icone: '👫',
    },
    {
      id: 'f15',
      texte: "Mange avec lui ce soir, assis ensemble. Éteins les écrans. 'La barakah se trouve dans le repas partagé.' Ce moment simple construit la connexion.",
      texteEN: "Have dinner with him tonight, sitting together. Turn off the screens. 'Barakah is found in the shared meal.' This simple moment builds connection.",
      source: "Ibn Majah",
      psycho: "Les repas partagés sans distraction créent un espace de connexion régulier essentiel à la vie conjugale.",
      psychoEN: "Shared meals without distraction create a regular connection space essential to married life.",
      icone: '🍽️',
    },
    {
      id: 'f16',
      texte: "Soutiens-le dans quelque chose qu'il fait aujourd'hui. Khadija (ra) soutenait le Prophète ﷺ avec sa richesse, sa foi et sa présence. C'est l'idéal de l'épouse.",
      texteEN: "Support him in something he is doing today. Khadijah (ra) supported the Prophet ﷺ with her wealth, faith, and presence. This is the ideal of the wife.",
      source: "Sahih al-Bukhari 3818",
      psycho: "Le soutien actif aux projets de son conjoint renforce la confiance en soi de l'autre et la solidarité du couple.",
      psychoEN: "Actively supporting your spouse's projects strengthens the other's self-confidence and the couple's solidarity.",
      icone: '💪',
    },
    {
      id: 'f17',
      texte: "Demande-lui comment il va vraiment — pas juste 'ça va ?' Écoute sans chercher à résoudre, juste pour comprendre.",
      texteEN: "Ask him how he really is — not just 'you okay?' Listen without trying to solve, just to understand.",
      source: "Psychologie du couple",
      psycho: "S'intéresser au vécu émotionnel de son conjoint sans chercher à 'réparer' immédiatement est une forme d'amour mature.",
      psychoEN: "Taking interest in your spouse's emotional life without immediately trying to 'fix' is a form of mature love.",
      icone: '👂',
    },
    {
      id: 'f18',
      texte: "Pardonne-lui quelque chose aujourd'hui — même sans qu'il le sache. Le pardon intérieur te libère toi avant de libérer la relation.",
      texteEN: "Forgive him something today — even without him knowing. Inner forgiveness frees you before it frees the relationship.",
      source: "Coran 24:22",
      psycho: "Le pardon intérieur, même sans réconciliation explicite, réduit le ressentiment et améliore le bien-être émotionnel.",
      psychoEN: "Inner forgiveness, even without explicit reconciliation, reduces resentment and improves emotional well-being.",
      icone: '🕊️',
    },
    {
      id: 'f19',
      texte: "Apprends quelque chose sur le dîn aujourd'hui et partage-le avec lui. Une épouse qui grandit spirituellement inspire son mari et élève le foyer.",
      texteEN: "Learn something about the deen today and share it with him. A wife who grows spiritually inspires her husband and elevates the home.",
      source: "Sagesse islamique",
      psycho: "La croissance personnelle et spirituelle est un facteur d'attractivité et d'admiration dans un couple.",
      psychoEN: "Personal and spiritual growth is a factor of attractiveness and admiration in a couple.",
      icone: '📖',
    },
    {
      id: 'f20',
      texte: "Planifie quelque chose de spécial pour lui cette semaine — même simple. Un plat préféré, une attention inattendue. L'inattendu réactive l'enthousiasme.",
      texteEN: "Plan something special for him this week — even simple. A favorite dish, an unexpected attention. The unexpected reactivates enthusiasm.",
      source: "Psychologie du couple",
      psycho: "La nouveauté et les surprises positives réactivent les circuits de la dopamine et maintiennent le désir dans la relation.",
      psychoEN: "Novelty and positive surprises reactivate dopamine circuits and maintain desire in the relationship.",
      icone: '🎁',
    },
    {
      id: 'f21',
      texte: "Observe ton mari aujourd'hui avec bienveillance. Cherche une qualité que tu n'avais pas remarquée depuis longtemps. L'attention consciente nourrit l'amour.",
      texteEN: "Observe your husband today with kindness. Find a quality you hadn't noticed in a long time. Conscious attention nourishes love.",
      source: "Psychologie positive",
      psycho: "Orienter intentionnellement son attention vers les qualités de l'autre réactive la perception positive fondatrice du couple.",
      psychoEN: "Intentionally directing one's attention toward the other's qualities reactivates the positive perception that founded the couple.",
      icone: '🌿',
    },
    {
      id: 'f22',
      texte: "Fixe une activité pour vous deux cette semaine. Une promenade, un café, quelque chose de simple. Les moments exclusifs au couple ne se créent pas seuls.",
      texteEN: "Schedule an activity for the two of you this week. A walk, a coffee, something simple. Exclusive couple moments don't create themselves.",
      source: "Psychologie du couple",
      psycho: "Les activités partagées régulières, même courtes, sont l'un des meilleurs investissements dans la vie conjugale.",
      psychoEN: "Regular shared activities, even short ones, are one of the best investments in married life.",
      icone: '🌙',
    },
    {
      id: 'f23',
      texte: "Évite les sujets de dispute habituels aujourd'hui. Certaines discussions ne méritent pas d'être relancées. La sagesse c'est de choisir ses batailles.",
      texteEN: "Avoid habitual argument topics today. Some discussions don't deserve to be restarted. Wisdom is choosing your battles.",
      source: "Psychologie islamique",
      psycho: "Savoir quelles discussions valent l'effort émotionnel est une compétence relationnelle essentielle qui préserve l'énergie du couple.",
      psychoEN: "Knowing which discussions are worth the emotional effort is an essential relational skill that preserves the couple's energy.",
      icone: '🚦',
    },
    {
      id: 'f24',
      texte: "Éteins ton téléphone lors du dîner ce soir. La présence totale est l'un des cadeaux les plus rares et les plus précieux qu'on puisse offrir à son conjoint.",
      texteEN: "Turn off your phone during dinner tonight. Total presence is one of the rarest and most precious gifts you can offer your spouse.",
      source: "Psychologie du couple",
      psycho: "L'attention totale sans distraction est une forme de respect profond qui signifie 'tu es ma priorité en ce moment'.",
      psychoEN: "Full attention without distraction is a form of deep respect that means 'you are my priority right now'.",
      icone: '📵',
    },
    {
      id: 'f25',
      texte: "Accepte un point de vue de ton mari aujourd'hui, même si tu n'es pas entièrement d'accord. La flexibilité relationnelle est une force, pas une faiblesse.",
      texteEN: "Accept one of your husband's points of view today, even if you're not entirely in agreement. Relational flexibility is a strength, not a weakness.",
      source: "Psychologie du couple",
      psycho: "La flexibilité cognitive dans un couple — accepter les perspectives différentes — réduit les conflits et renforce le respect mutuel.",
      psychoEN: "Cognitive flexibility in a couple — accepting different perspectives — reduces conflict and strengthens mutual respect.",
      icone: '🤝',
    },
    {
      id: 'f26',
      texte: "Fais quelque chose qu'il t'a demandé depuis longtemps. Honorer ses demandes montre que ses paroles comptent vraiment pour toi.",
      texteEN: "Do something he has asked you to do for a long time. Honoring his requests shows that his words truly matter to you.",
      source: "Psychologie du couple",
      psycho: "Répondre à une demande ancienne montre que les paroles de son conjoint sont retenues et valorisées, créant un sentiment d'être entendu.",
      psychoEN: "Responding to an old request shows that your spouse's words are remembered and valued, creating a feeling of being heard.",
      icone: '✅',
    },
    {
      id: 'f27',
      texte: "Réserve ce soir un moment de calme avec lui. Pas forcément pour parler — juste être côte à côte. La proximité silencieuse est une forme d'intimité profonde.",
      texteEN: "Reserve a quiet moment with him this evening. Not necessarily to talk — just to be side by side. Silent closeness is a form of deep intimacy.",
      source: "Psychologie de l'attachement",
      psycho: "La coprésence paisible — être ensemble sans obligation de communication — est une forme d'intimité particulièrement sécurisante.",
      psychoEN: "Peaceful co-presence — being together without the obligation to communicate — is a particularly reassuring form of intimacy.",
      icone: '🌿',
    },
    {
      id: 'f28',
      texte: "Fais du dhikr pour ton foyer ce matin. 'Subhanallah, Alhamdulillah, Allahu Akbar.' Commencer la journée par la gratitude oriente l'esprit vers le bien.",
      texteEN: "Do dhikr for your home this morning. 'Subhanallah, Alhamdulillah, Allahu Akbar.' Starting the day with gratitude orients the mind toward good.",
      source: "Tradition prophétique",
      psycho: "Les pratiques de gratitude matinales améliorent l'humeur générale et la perception positive de sa vie conjugale.",
      psychoEN: "Morning gratitude practices improve overall mood and positive perception of one's married life.",
      icone: '🤲',
    },
    {
      id: 'f29',
      texte: "Parle à ton mari de vos rêves communs. Où voulez-vous être dans 5 ans ? Les couples qui ont une vision partagée traversent mieux les épreuves.",
      texteEN: "Talk to your husband about your shared dreams. Where do you want to be in 5 years? Couples with a shared vision better weather hardships.",
      source: "Psychologie du couple",
      psycho: "Une vision commune du futur couple est un facteur de protection majeur contre la dégradation de la relation dans le temps.",
      psychoEN: "A shared vision of the couple's future is a major protective factor against the deterioration of the relationship over time.",
      icone: '🌟',
    },
    {
      id: 'f30',
      texte: "Dis-lui bonne nuit avec une parole douce ce soir. 'Les meilleurs des hommes sont lents à la colère et prompts à se réconcilier.' (Musnad Ahmad 11143) Finir la journée en paix prépare le lendemain.",
      texteEN: "Wish him good night with a gentle word this evening. 'The best of men are slow to anger and quick to be appeased.' (Musnad Ahmad 11143) Ending the day in peace prepares tomorrow.",
      source: "Sirah",
      psycho: "Les interactions positives de fin de journée ont un effet neurologique durable — elles conditionnent la qualité du lien au réveil.",
      psychoEN: "Positive end-of-day interactions have a lasting neurological effect — they condition the quality of the bond upon waking.",
      icone: '🌙',
    },
  ],
};

// ─── FICHES PRATIQUES ────────────────────────────────────────────────────────
export const FICHES = [
  {
    id: 'f1',
    titre: "La communication dans le couple",
    titreEN: "Communication in the couple",
    categorie: "Communication",
    emoji: '💬',
    couleur: '#4A7C59',
    resume: "Comment se parler avec bienveillance et efficacité.",
    resumeEN: "Learn to express yourself and truly listen to your spouse",
    contenu: [
      {
        sousTitre: "Ce qu'enseigne l'Islam",
        texte: "Allah dit : 'Parlez-leur de façon convenable' (Coran 4:5). Le Prophète ﷺ ne criait jamais sur ses épouses et ne les insultait jamais. Il exprimait ses besoins et ses désaccords avec douceur et clarté.",
        texteEN: "Allah says: 'Speak to them with kindness' (Quran 4:5). The Prophet ﷺ never shouted at his wives and never insulted them. He expressed his needs and disagreements with gentleness and clarity.",
      },
      {
        sousTitre: "Les erreurs courantes",
        texte: "• Parler sous le coup de la colère\n• Critiquer la personne plutôt que le comportement\n• Garder les non-dits qui s'accumulent\n• Interrompre sans écouter",
        texteEN: "• Speaking in anger\n• Criticizing the person rather than the behavior\n• Letting unspoken things accumulate\n• Interrupting without listening",
      },
      {
        sousTitre: "La technique islamique & psychologique",
        texte: "1. Commence par le salam et un compliment sincère\n2. Exprime ce que tu ressens (pas ce que l'autre a 'mal fait')\n3. Dis clairement ce dont tu as besoin\n4. Termine par de la gratitude\n\nExemple : 'Je t'aime et j'apprécie tout ce que tu fais. Quand tu rentres tard sans prévenir, je me sens anxieuse. J'aurais besoin que tu m'envoies un message dans ce cas. Merci de m'écouter.'",
        texteEN: "1. Start with salam and a sincere compliment\n2. Express what you feel (not what the other 'did wrong')\n3. Clearly state what you need\n4. End with gratitude\n\nExample: 'I love you and appreciate everything you do. When you come home late without letting me know, I feel anxious. I would need you to send me a message in that case. Thank you for listening.'",
      },
      {
        sousTitre: "Le défi du jour",
        texte: "Parle à ton conjoint de quelque chose qui te tient à cœur, en utilisant la formule : 'Quand tu fais X, je ressens Y, j'aurais besoin de Z.'",
        texteEN: "Talk to your spouse about something important to you, using the formula: 'When you do X, I feel Y, I would need Z.'",
      },
    ],
  },
  {
    id: 'f2',
    titre: "Gérer les conflits sainement",
    titreEN: "Managing conflicts healthily",
    categorie: "Conflits",
    emoji: '🕊️',
    couleur: '#3B6EA5',
    resume: "Transformer les disputes en opportunités de rapprochement.",
    resumeEN: "Transform tensions into opportunities for growth",
    contenu: [
      {
        sousTitre: "La perspective islamique",
        texte: "Le Prophète ﷺ a dit : 'Le fort n'est pas celui qui terrasse les autres, mais celui qui se maîtrise dans la colère.' Chaque dispute est une épreuve et une opportunité de grandir ensemble.",
        texteEN: "The Prophet ﷺ said: 'The strong person is not the one who overpowers others, but the one who controls themselves in anger.' Every argument is a trial and an opportunity to grow together.",
      },
      {
        sousTitre: "La règle des 3 pauses",
        texte: "1. PAUSE physique : si la colère monte, quitte la pièce 10 minutes\n2. PAUSE spirituelle : dis Astaghfirullah et A'oudhou billahi mina shaytani rajim\n3. PAUSE réflexive : demande-toi 'Est-ce que ce sujet vaut vraiment la peine d'une dispute ?'",
        texteEN: "1. PHYSICAL pause: if anger rises, leave the room for 10 minutes\n2. SPIRITUAL pause: say Astaghfirullah and A'oudhou billahi mina shaytani rajim\n3. REFLECTIVE pause: ask yourself 'Is this topic really worth an argument?'",
      },
      {
        sousTitre: "Les 5 erreurs à éviter",
        texte: "❌ Ressortir les vieilles rancœurs\n❌ Impliquer la famille ou les amis\n❌ Menacer de divorce dans la colère\n❌ Dormir sans tenter de réconciliation (la rancœur grandit pendant la nuit)\n❌ Critiquer devant les enfants",
        texteEN: "❌ Bringing up old grievances\n❌ Involving family or friends\n❌ Threatening divorce in anger\n❌ Going to sleep without attempting reconciliation (resentment grows overnight)\n❌ Criticizing in front of children",
      },
      {
        sousTitre: "La réconciliation islamique",
        texte: "Le Prophète ﷺ initiait toujours la réconciliation. Faire le premier pas n'est pas une faiblesse, c'est de la grandeur d'âme. Un 'je suis désolé' sincère peut changer toute une relation.",
        texteEN: "The Prophet ﷺ always initiated reconciliation. Taking the first step is not weakness, it is greatness of soul. A sincere 'I'm sorry' can transform an entire relationship.",
      },
    ],
  },
  {
    id: 'f3',
    titre: "Les droits & devoirs dans le couple",
    titreEN: "Rights and duties in the couple",
    categorie: "Droits",
    emoji: '⚖️',
    couleur: '#C9A84C',
    resume: "Ce que l'Islam prescrit pour chaque époux.",
    resumeEN: "Understanding your respective roles in Islam",
    contenu: [
      {
        sousTitre: "Les droits de l'épouse",
        texte: "• La mahr (dot) et son maintien\n• La nafaqa : logement, nourriture, vêtements selon les moyens\n• Le respect, la douceur et la bienveillance\n• Le droit à l'intimité émotionnelle et physique\n• Ne pas être frappée ni insultée\n• Le temps, la présence et l'attention",
        texteEN: "• The mahr (dowry) and its fulfillment\n• The nafaqa: housing, food, clothing according to means\n• Respect, gentleness and kindness\n• The right to emotional and physical intimacy\n• Not to be hit or insulted\n• Time, presence and attention",
      },
      {
        sousTitre: "Les droits du mari",
        texte: "• L'obéissance dans les choses licites\n• Le respect de son autorité bienveillante\n• La gestion du foyer et l'accueil chaleureux\n• La fidélité et la préservation de sa réputation\n• Le soutien émotionnel",
        texteEN: "• Obedience in lawful matters\n• Respect for his benevolent authority\n• Management of the household and warm welcome\n• Fidelity and preservation of his reputation\n• Emotional support",
      },
      {
        sousTitre: "L'équilibre islamique",
        texte: "'Elles ont des droits équivalents à leurs obligations, selon les règles établies.' (Coran 2:228). L'Islam ne prône pas la domination mais la complémentarité et la coopération entre époux.",
        texteEN: "'They have rights equivalent to their obligations, according to established rules.' (Quran 2:228). Islam does not advocate domination but complementarity and cooperation between spouses.",
      },
    ],
  },
  {
    id: 'f4',
    titre: "L'intimité dans le couple",
    titreEN: "Intimacy in the couple",
    categorie: "Intimité",
    emoji: '❤️',
    couleur: '#A05A7A',
    resume: "Préserver et nourrir l'intimité émotionnelle et physique.",
    resumeEN: "Nourishing physical and emotional closeness",
    contenu: [
      {
        sousTitre: "L'Islam et l'intimité",
        texte: "Le Prophète ﷺ était tendre, affectueux et attentif avec ses épouses. Il les embrassait, jouait avec elles, les écoutait. L'intimité dans le mariage est une ibada, un acte d'adoration.",
        texteEN: "The Prophet ﷺ was tender, affectionate and attentive with his wives. He embraced them, played with them, listened to them. Intimacy in marriage is an ibada, an act of worship.",
      },
      {
        sousTitre: "Les 4 niveaux d'intimité",
        texte: "1. Physique : les gestes de tendresse quotidiens (toucher, câlin)\n2. Émotionnelle : partager ses peurs, ses rêves, ses vulnérabilités\n3. Intellectuelle : discuter, s'enrichir mutuellement\n4. Spirituelle : prier ensemble, faire dua l'un pour l'autre",
        texteEN: "1. Physical: daily gestures of tenderness (touch, hugs)\n2. Emotional: sharing fears, dreams, vulnerabilities\n3. Intellectual: discussing, enriching each other mutually\n4. Spiritual: praying together, making dua for one another",
      },
      {
        sousTitre: "Préserver le désir sur le long terme",
        texte: "• Continuer à prendre soin de soi\n• Créer des rituels d'intimité (dîner sans écrans, promenade)\n• Surprendre son conjoint régulièrement\n• Exprimer son amour verbalement et physiquement\n• Préserver la nouveauté et l'inattendu",
        texteEN: "• Continue to take care of yourself\n• Create intimacy rituals (screen-free dinner, walks)\n• Surprise your spouse regularly\n• Express your love verbally and physically\n• Preserve novelty and the unexpected",
      },
    ],
  },
  {
    id: 'f5',
    titre: "Élever les enfants ensemble",
    titreEN: "Raising children together",
    categorie: "Famille",
    emoji: '👨‍👩‍👧',
    couleur: '#4A7C59',
    resume: "Comment éduquer en couple, avec cohérence et amour.",
    resumeEN: "Aligning your educational visions",
    contenu: [
      {
        sousTitre: "Le couple, fondation de la famille",
        texte: "La meilleure chose que vous puissiez donner à vos enfants est de vous aimer mutuellement et de le montrer. Les enfants apprennent l'amour en observant leurs parents.",
        texteEN: "The best thing you can give your children is to love each other and show it. Children learn about love by observing their parents.",
      },
      {
        sousTitre: "Les principes islamiques d'éducation",
        texte: "• Éduquer par l'exemple avant les mots\n• Être cohérents dans vos décisions (ne pas se contredire devant les enfants)\n• Montrer de l'affection physique et verbale\n• Enseigner l'Islam par la douceur et l'amour\n• Faire des dua ensemble pour vos enfants",
        texteEN: "• Educate by example before words\n• Be consistent in your decisions (don't contradict each other in front of the children)\n• Show physical and verbal affection\n• Teach Islam through gentleness and love\n• Make dua together for your children",
      },
      {
        sousTitre: "Éviter les erreurs classiques",
        texte: "❌ Se disputer devant les enfants sur leur éducation\n❌ Laisser les enfants diviser le couple\n❌ Surprotéger ou au contraire négliger\n❌ Utiliser les enfants comme messagers lors des conflits",
        texteEN: "❌ Arguing in front of children about their upbringing\n❌ Letting children divide the couple\n❌ Overprotecting or, on the contrary, neglecting\n❌ Using children as messengers during conflicts",
      },
    ],
  },
  {
    id: 'f6',
    titre: "Maintenir l'amour sur le long terme",
    titreEN: "Maintaining love long-term",
    categorie: "Amour",
    emoji: '🌹',
    couleur: '#C9A84C',
    resume: "Le mariage n'est pas une destination, c'est un voyage.",
    resumeEN: "Keeping the flame alive over the years",
    contenu: [
      {
        sousTitre: "L'amour selon l'Islam",
        texte: "'Parmi Ses signes, Il a créé pour vous, de vous-mêmes, des épouses afin que vous viviez en tranquillité auprès d'elles, et Il a mis entre vous de l'affection et de la bienveillance.' (Coran 30:21)",
        texteEN: "'Among His signs is that He created for you from yourselves spouses that you may find tranquility in them, and He placed between you affection and mercy.' (Quran 30:21)",
      },
      {
        sousTitre: "Les 5 langages de l'amour",
        texte: "Comprendre comment votre conjoint se sent aimé :\n1. Les paroles valorisantes ('Je suis fier(e) de toi')\n2. Les moments de qualité (temps dédié, sans distractions)\n3. Les cadeaux (même petits et symboliques)\n4. Les services rendus (aider sans qu'on le demande)\n5. Le toucher physique (caresses, main dans la main)",
        texteEN: "Understanding how your spouse feels loved:\n1. Words of affirmation ('I'm proud of you')\n2. Quality time (dedicated time, without distractions)\n3. Gifts (even small and symbolic ones)\n4. Acts of service (helping without being asked)\n5. Physical touch (caresses, holding hands)",
      },
      {
        sousTitre: "Les rituels qui maintiennent l'amour",
        texte: "• Une sortie en amoureux par mois minimum\n• Se coucher à la même heure régulièrement\n• Un message affectueux chaque matin\n• Prier ensemble au moins une fois par jour\n• Se rappeler mutuellement vos débuts",
        texteEN: "• At least one couple outing per month\n• Going to bed at the same time regularly\n• An affectionate message every morning\n• Praying together at least once a day\n• Reminding each other of your early days",
      },
    ],
  },
  {
    id: 'f7',
    titre: "La belle-famille : gérer les limites",
    titreEN: "In-laws: setting boundaries",
    categorie: "Famille élargie",
    emoji: '🏠',
    couleur: '#3B6EA5',
    resume: "Honorer sa famille tout en protégeant son couple.",
    resumeEN: "Protecting your couple while respecting family",
    contenu: [
      {
        sousTitre: "Le principe islamique",
        texte: "L'Islam ordonne d'honorer ses parents ET de protéger son foyer. Ces deux obligations ne s'excluent pas. Le nouveau foyer créé par le mariage est une entité distincte et sacrée.",
        texteEN: "Islam commands honoring parents AND protecting the home. These two obligations are not mutually exclusive. The new home created by marriage is a distinct and sacred entity.",
      },
      {
        sousTitre: "Poser des limites sainement",
        texte: "• Présenter un front uni avec ton conjoint\n• Ne jamais critiquer la famille de l'autre en public\n• Discuter des limites entre époux, pas devant la famille\n• Les décisions du foyer appartiennent aux époux\n• Le respect de la belle-famille ne signifie pas obéissance totale",
        texteEN: "• Present a united front with your spouse\n• Never criticize the other's family in public\n• Discuss boundaries between spouses, not in front of family\n• Household decisions belong to the spouses\n• Respect for in-laws does not mean total obedience",
      },
      {
        sousTitre: "Quand la belle-famille interfère",
        texte: "1. En parler calmement avec son conjoint en privé\n2. Trouver ensemble une solution\n3. C'est à chaque époux de parler à SA propre famille\n4. Faire dua pour la paix et la sagesse\n5. Si besoin, consulter un imam ou un médiateur",
        texteEN: "1. Talk calmly with your spouse in private\n2. Find a solution together\n3. Each spouse should talk to THEIR OWN family\n4. Make dua for peace and wisdom\n5. If needed, consult an imam or mediator",
      },
    ],
  },
  {
    id: 'f8',
    titre: "Traverser les épreuves ensemble",
    titreEN: "Facing trials together",
    categorie: "Résilience",
    emoji: '🌿',
    couleur: '#4A7C59',
    resume: "Transformer les difficultés en force commune.",
    resumeEN: "Strengthening your bond through difficult times",
    contenu: [
      {
        sousTitre: "L'épreuve, une opportunité de rapprochement",
        texte: "Les couples qui traversent les épreuves ensemble et qui s'appuient mutuellement sur Allah sortent généralement plus soudés. L'épreuve teste et révèle la solidité du lien.",
        texteEN: "Couples who face trials together and lean on Allah together generally come out more united. Trials test and reveal the strength of the bond.",
      },
      {
        sousTitre: "Les réflexes islamiques dans l'épreuve",
        texte: "• 'Inna lillahi wa inna ilayhi raji'oun' - revenir à Allah ensemble\n• Faire dua l'un pour l'autre et ensemble\n• Se rappeler mutuellement la récompense de la patience\n• Ne pas se retourner l'un contre l'autre dans la difficulté\n• Chercher du soutien (imam, famille de confiance, psy)",
        texteEN: "• 'Inna lillahi wa inna ilayhi raji'oun' — return to Allah together\n• Make dua for each other and together\n• Remind each other of the reward of patience\n• Do not turn against each other in difficulty\n• Seek support (imam, trusted family, therapist)",
      },
      {
        sousTitre: "Les outils psychologiques",
        texte: "• Identifier ensemble ce qui est dans votre contrôle\n• Se soutenir émotionnellement sans résoudre à la place de l'autre\n• Maintenir les rituels positifs (repas ensemble, prières)\n• Célébrer les petites victoires\n• Demander de l'aide professionnelle si nécessaire",
        texteEN: "• Identify together what is within your control\n• Support each other emotionally without solving things for the other\n• Maintain positive rituals (meals together, prayers)\n• Celebrate small victories\n• Seek professional help if necessary",
      },
    ],
  },
  {
    id: 'f9',
    titre: "L'argent dans le couple",
    titreEN: "Money in the couple",
    categorie: "Finance",
    emoji: '💰',
    couleur: '#C9A84C',
    resume: "Gérer l'argent avec transparence et sérénité islamique.",
    resumeEN: "Managing finances with transparency and trust",
    contenu: [
      {
        sousTitre: "La perspective islamique",
        texte: "En Islam, le mari a l'obligation de subvenir aux besoins du foyer (nafaqa). Les revenus de la femme, quant à eux, lui appartiennent entièrement — à elle seule. Ce cadre crée une asymétrie claire qui demande maturité et dialogue.",
        texteEN: "In Islam, the husband has the obligation to provide for the household (nafaqa). The wife's income, on the other hand, belongs entirely to her alone. This framework creates a clear asymmetry that requires maturity and dialogue.",
      },
      {
        sousTitre: "Les erreurs financières qui détruisent les couples",
        texte: "❌ Cacher des dettes ou des dépenses à son conjoint\n❌ Dépenser l'argent du foyer sans concertation\n❌ Reprocher à sa femme de ne pas contribuer financièrement (ce n'est pas une obligation islamique)\n❌ Utiliser l'argent comme moyen de contrôle ou de pression\n❌ Ne pas parler d'argent jusqu'à ce que la situation soit critique",
        texteEN: "❌ Hiding debts or expenses from your spouse\n❌ Spending household money without consultation\n❌ Blaming your wife for not contributing financially (this is not an Islamic obligation)\n❌ Using money as a means of control or pressure\n❌ Not talking about money until the situation becomes critical",
      },
      {
        sousTitre: "Construire ensemble une saine gestion",
        texte: "• Fixer ensemble les objectifs financiers du foyer\n• Avoir une réunion mensuelle sur les finances\n• Définir clairement qui paie quoi\n• Constituer une épargne commune (ex: pour la Oumra, les enfants)\n• Respecter le budget et éviter les dépenses cachées",
        texteEN: "• Set household financial goals together\n• Have a monthly meeting about finances\n• Define clearly who pays for what\n• Build common savings (e.g., for Umrah, children)\n• Respect the budget and avoid hidden expenses",
      },
      {
        sousTitre: "Le hadith de la générosité",
        texte: "'Ce que tu dépenses pour ta famille est une sadaqa.' (Bukhari). La dépense pour son foyer est un acte d'adoration. Cela change radicalement la perspective sur l'argent du ménage.",
        texteEN: "'What you spend for your family is a sadaqa.' (Bukhari). Spending on your household is an act of worship. This radically changes the perspective on household finances.",
      },
    ],
  },
  {
    id: 'f10',
    titre: "Le Ramadan en couple",
    titreEN: "Ramadan as a couple",
    categorie: "Spiritualité",
    emoji: '🌙',
    couleur: '#3B6EA5',
    resume: "Faire du mois sacré un moment de rapprochement profond.",
    resumeEN: "Making this blessed month a time of renewal",
    contenu: [
      {
        sousTitre: "Le Ramadan, opportunité unique pour le couple",
        texte: "Le Ramadan est le moment idéal pour se reconstruire spirituellement ensemble. Le jeûne, la prière, le Coran partagés créent une intimité spirituelle rare que rien d'autre ne peut remplacer.",
        texteEN: "Ramadan is the ideal time to rebuild spiritually together. Fasting, prayer, and Quran shared together create a rare spiritual intimacy that nothing else can replace.",
      },
      {
        sousTitre: "5 pratiques du couple en Ramadan",
        texte: "1. Se lever ensemble pour le suhour et y faire une courte prière\n2. Lire le Coran ensemble, même 5 minutes par jour\n3. Rompre le jeûne ensemble, sans écrans, avec gratitude\n4. Prier tarawih ensemble à la maison si possible\n5. Partager chaque soir une chose apprise spirituellement",
        texteEN: "1. Wake up together for suhour and make a short prayer\n2. Read the Quran together, even 5 minutes a day\n3. Break the fast together, without screens, with gratitude\n4. Pray tarawih together at home if possible\n5. Share each evening one thing learned spiritually",
      },
      {
        sousTitre: "Éviter les tensions du Ramadan",
        texte: "La fatigue et la faim peuvent exacerber les tensions :\n• Ne pas avoir de discussions importantes en fin de journée\n• Se montrer particulièrement patient et doux\n• Répartir équitablement les tâches ménagères\n• Dormir suffisamment pour ne pas être à fleur de peau",
        texteEN: "Fatigue and hunger can exacerbate tensions:\n• Avoid important discussions late in the day\n• Be particularly patient and gentle\n• Share household tasks equitably\n• Get enough sleep to avoid being on edge",
      },
      {
        sousTitre: "La nuit du Qadr en couple",
        texte: "Les 10 dernières nuits sont une opportunité extraordinaire. Faites ensemble une liste de dua pour votre mariage, vos enfants, votre avenir. Ces moments de supplication commune créent des liens indéfectibles.",
        texteEN: "The last 10 nights are an extraordinary opportunity. Make together a list of duas for your marriage, your children, your future. These moments of shared supplication create unbreakable bonds.",
      },
    ],
  },
  {
    id: 'f11',
    titre: "Surmonter une crise conjugale",
    titreEN: "Overcoming a marital crisis",
    categorie: "Crise",
    emoji: '💔',
    couleur: '#A05A7A',
    resume: "Quand le couple traverse une tempête — que faire ?",
    resumeEN: "Rebuilding after a difficult period",
    contenu: [
      {
        sousTitre: "La crise fait partie du mariage",
        texte: "Aucun couple n'est épargné par les crises. Ce qui distingue les couples qui durent, ce n'est pas l'absence de crises, mais la façon dont ils les traversent ensemble. Une crise bien gérée peut même renforcer le couple.",
        texteEN: "No couple is spared from crises. What distinguishes couples who last is not the absence of crises, but how they go through them together. A well-managed crisis can even strengthen the couple.",
      },
      {
        sousTitre: "Les signes d'une crise sérieuse",
        texte: "• Plus de communication ou communication toxique\n• Absence d'intimité physique prolongée\n• Mépris ou indifférence persistante\n• Pensées régulières de séparation\n• Violence verbale ou physique (nécessite une aide immédiate)",
        texteEN: "• No communication or toxic communication\n• Prolonged absence of physical intimacy\n• Persistent contempt or indifference\n• Regular thoughts of separation\n• Verbal or physical violence (requires immediate help)",
      },
      {
        sousTitre: "Les étapes islamiques de la réconciliation",
        texte: "1. Istighfar personnel : commence par ta part de responsabilité\n2. Faire dua sincère pour ton couple\n3. Chercher un médiateur de confiance (imam, personne sage)\n4. L'arbitrage islamique (Coran 4:35)\n5. La thérapie de couple si nécessaire — ce n'est pas un aveu d'échec",
        texteEN: "1. Personal istighfar: start with your share of responsibility\n2. Make sincere dua for your relationship\n3. Seek a trusted mediator (imam, wise person)\n4. Islamic arbitration (Quran 4:35)\n5. Couples therapy if necessary — it is not an admission of failure",
      },
      {
        sousTitre: "Ce qui ne règle rien",
        texte: "❌ Le silence prolongé\n❌ Impliquer les enfants dans le conflit\n❌ Raconter les problèmes à tout l'entourage\n❌ Les ultimatums répétés\n❌ Attendre que l'autre fasse le premier pas indéfiniment",
        texteEN: "❌ Prolonged silence\n❌ Involving children in the conflict\n❌ Telling everyone about your problems\n❌ Repeated ultimatums\n❌ Waiting indefinitely for the other to make the first move",
      },
    ],
  },
  {
    id: 'f12',
    titre: "La spiritualité dans le couple",
    titreEN: "Spirituality in the couple",
    categorie: "Spiritualité",
    emoji: '🤲',
    couleur: '#4A7C59',
    resume: "Allah au centre du foyer — construire ensemble vers l'Au-delà.",
    resumeEN: "Growing together in faith",
    contenu: [
      {
        sousTitre: "Le foyer islamique idéal",
        texte: "Le Prophète ﷺ a dit : 'Qu'Allah fasse miséricorde à l'homme qui se lève la nuit pour prier et réveille sa femme.' (Abu Dawud). La spiritualité partagée est le plus solide des ciments conjugaux.",
        texteEN: "The Prophet ﷺ said: 'May Allah have mercy on the man who gets up at night to pray and wakes his wife.' (Abu Dawud). Shared spirituality is the strongest cement of marriage.",
      },
      {
        sousTitre: "Les pratiques spirituelles communes",
        texte: "• Prier ensemble au moins une fois par jour\n• Lire un verset du Coran avec son tafsir\n• Faire dua l'un pour l'autre, en sa présence\n• Donner la sadaqa ensemble\n• Célébrer les moments forts de l'Islam (Aid, Ramadan)",
        texteEN: "• Pray together at least once a day\n• Read a verse of the Quran with its tafsir\n• Make dua for each other, in their presence\n• Give sadaqa together\n• Celebrate the key moments of Islam (Eid, Ramadan)",
      },
      {
        sousTitre: "Le dua du couple",
        texte: "'Rabbana hab lana min azwajina wa dhurriyyatina qurrata a\'yunin' — Notre Seigneur, accorde-nous de nos épouses et de notre descendance la joie des yeux. (Coran 25:74)\n\nRécite ce dua ensemble chaque soir.",
        texteEN: "'Rabbana hab lana min azwajina wa dhurriyyatina qurrata a\'yunin' — Our Lord, grant us from our spouses and offspring comfort to our eyes. (Quran 25:74)\n\nRecite this dua together every evening.",
      },
      {
        sousTitre: "Quand les niveaux de pratique diffèrent",
        texte: "Ne jamais forcer, toujours inviter par l'exemple et la douceur. Le Prophète ﷺ n'a jamais contraint — il inspirait. Ta propre progression spirituelle est le meilleur moyen d'entraîner ton conjoint vers le bien.",
        texteEN: "Never force, always invite through example and gentleness. The Prophet ﷺ never coerced — he inspired. Your own spiritual progress is the best way to draw your spouse towards good.",
      },
    ],
  },
  {
    id: 'f13',
    titre: "Demander pardon & se réconcilier",
    titreEN: "Asking forgiveness & reconciling",
    categorie: "Réconciliation",
    emoji: '🕊️',
    couleur: '#4A7C59',
    resume: "L'art islamique de demander pardon et de pardonner.",
    resumeEN: "The art of sincere reconciliation in Islam",
    contenu: [
      {
        sousTitre: "Pourquoi c'est si difficile",
        texte: "Demander pardon demande de l'humilité — une qualité que l'ego résiste naturellement. Pourtant, dans l'Islam, l'humilité est une force. Le Prophète ﷺ était le premier à se réconcilier après une tension.",
        texteEN: "Asking forgiveness requires humility — a quality the ego naturally resists. Yet in Islam, humility is a strength. The Prophet ﷺ was the first to reconcile after a tension.",
      },
      {
        sousTitre: "Comment demander pardon sincèrement",
        texte: "Un vrai pardon comporte 4 éléments :\n1. Reconnaître clairement ('J'ai eu tort de...')\n2. Exprimer du regret sincère sans 'mais'\n3. Demander explicitement pardon\n4. S'engager à changer\n\nÀ éviter : 'Excuse-moi si tu t'es senti blessé' — c'est conditionnel.",
        texteEN: "A genuine apology has 4 elements:\n1. Acknowledge clearly ('I was wrong to...')\n2. Express sincere regret without 'but'\n3. Explicitly ask for forgiveness\n4. Commit to change\n\nTo avoid: 'Sorry if you felt hurt' — this is conditional.",
      },
      {
        sousTitre: "Comment pardonner vraiment",
        texte: "Pardonner ne signifie pas oublier. C'est choisir de ne pas laisser la blessure empoisonner la relation.\n\n'N'aimez-vous pas qu'Allah vous pardonne ?' (Coran 24:22). Le pardon que tu donnes te rapproche du pardon d'Allah.",
        texteEN: "Forgiving does not mean forgetting. It is choosing not to let the wound poison the relationship.\n\n'Would you not like that Allah should forgive you?' (Quran 24:22). The forgiveness you give draws you closer to Allah's forgiveness.",
      },
      {
        sousTitre: "Le rituel de réconciliation",
        texte: "Après la réconciliation :\n• Faire ablution ensemble\n• Prier 2 rakats\n• Dire 'Je t'aime pour l'amour d'Allah'\n• Tourner la page définitivement — ne plus ressortir le sujet",
        texteEN: "After reconciliation:\n• Make wudu together\n• Pray 2 rakats\n• Say 'I love you for the sake of Allah'\n• Turn the page definitively — never bring the subject up again",
      },
    ],
  },
,
  {
    id: 'd5',
    titre: "Le Ramadan en couple",
    description: "Faites de ce Ramadan le plus spirituel de votre vie conjugale.",
    duree: "7 jours",
    difficulte: "Moyen",
    emoji: '🌙',
    jours: [
      "Levez-vous ensemble pour le suhour et faites une courte prière.",
      "Lisez ensemble un verset du Coran avec son explication.",
      "Rompez le jeûne ensemble sans télévision ni téléphone.",
      "Priez ensemble tarawih à la maison ce soir.",
      "Partagez chaque soir une chose apprise spirituellement.",
      "Faites ensemble une liste de dua pour votre famille et votre avenir.",
      "Passez la nuit à prier ensemble. Cherchez le Qadr côte à côte.",
    ],
  },
  {
    id: 'd6',
    titre: "L'intimité émotionnelle",
    description: "Redécouvrez-vous l'un l'autre en profondeur.",
    duree: "5 jours",
    difficulte: "Moyen",
    emoji: '💞',
    jours: [
      "Partagez chacun votre plus grande peur. Écoutez sans jugement.",
      "Racontez-vous votre plus beau souvenir ensemble. Revivez-le.",
      "Dites-vous 3 rêves que vous n'avez jamais osé partager.",
      "Parlez de votre enfance. Ce qui vous a construit. Ce que vous voulez transmettre.",
      "Répondez ensemble : Dans 10 ans, je veux qu'on soit... Construisez la vision.",
    ],
  },
  {
    id: 'd7',
    titre: "Belle-famille sereine",
    description: "Établissez des bases saines avec vos familles respectives.",
    duree: "7 jours",
    difficulte: "Difficile",
    emoji: '🏡',
    jours: [
      "Discutez ensemble : quelles sont les limites saines avec nos familles ?",
      "Chacun appelle SA famille. Aucune interférence de l'autre.",
      "Listez les tensions liées aux familles. Priorisez-les ensemble.",
      "Pour chaque tension : décidez ensemble d'une réponse commune.",
      "Appliquez une limite décidée ensemble. Faites-le avec respect.",
      "Remerciez vos familles pour ce qu'elles vous ont apporté.",
      "Évaluez : qu'est-ce qui a changé dans la gestion des familles cette semaine ?",
    ],
  },
  {
    id: 'd8',
    titre: "Finances transparentes",
    description: "Mettez les cartes sur table et construisez ensemble.",
    duree: "5 jours",
    difficulte: "Difficile",
    emoji: '💰',
    jours: [
      "Partagez honnêtement revenus et dépenses actuels. Sans jugement.",
      "Identifiez ensemble 3 objectifs financiers communs (Oumra, épargne...).",
      "Définissez qui paie quoi. La clarté évite les rancœurs.",
      "Identifiez les dépenses sources de tension. Proposez des solutions.",
      "Faites dua ensemble pour la barakah dans vos revenus et votre foyer.",
    ],
  },
  {
    id: 'd9',
    titre: "Défi réconciliation",
    description: "Guérissez les blessures passées et repartez sur de nouvelles bases.",
    duree: "7 jours",
    difficulte: "Difficile",
    emoji: '🕊️',
    jours: [
      "Chacun écrit les 3 blessures passées qu'il n'a pas encore vraiment pardonnées.",
      "Chacun demande pardon pour SA part de responsabilité.",
      "Définissez ensemble 3 règles pour éviter les mêmes schémas.",
      "Faites 2 rakats ensemble pour demander à Allah de purifier votre relation.",
      "Déchirez symboliquement vos listes de blessures. Tournez la page.",
      "Passez une journée sans évoquer le passé. Vivez dans le présent.",
      "Rédigez ensemble votre nouveau départ : comment vous voulez être désormais.",
    ],
  },
  {
    id: 'd10',
    titre: "Spiritualité partagée",
    description: "Faites d'Allah le centre de votre foyer.",
    duree: "7 jours",
    difficulte: "Facile",
    emoji: '🤲',
    jours: [
      "Priez ensemble au moins une prière par jour toute la semaine.",
      "Lisez ensemble le tafsir d'un verset sur le mariage.",
      "Faites du dhikr ensemble 10 minutes avant de dormir.",
      "Donnez la sadaqa ensemble — même 1€. Décidez ensemble à qui.",
      "Apprenez un dua pour le couple. Récitez-le ensemble ce soir.",
      "Parlez de ce que vous voulez construire spirituellement comme famille.",
      "Terminez par une longue dua commune. Dites à Allah tout ce que vous souhaitez.",
    ],
  },
];

// ─── HADITHS DU COUPLE (30 jours) ───────────────────────────────────────────
export const HADITHS = [
  {
    id: 'had1',
    texte: "Le meilleur d'entre vous est celui qui est le meilleur envers sa famille, et je suis le meilleur d'entre vous envers ma famille.",
    texteEN: "The best of you is the one who is best to his family, and I am the best of you to my family.",
    source: "Tirmidhi - Sahih",
    explication: "La noblesse d'un homme ou d'une femme se mesure d'abord à la qualité de ses relations au sein de son foyer, avant tout rôle public.",
    explicacionEN: "A person's nobility is first measured by the quality of their home relationships, before any public role.",
    emoji: '⭐',
  },
  {
    id: 'had2',
    texte: "Traitez les femmes avec bonté. La femme a été créée d'une côte, et la partie la plus recourbée de la côte est le haut. Si tu essaies de la redresser, tu la casseras. Prends-en soin.",
    texteEN: "Treat women kindly. Woman was created from a rib, and the most curved part of a rib is the top. If you try to straighten it you will break it. Take care of her.",
    source: "Sahih al-Bukhari 5184",
    explication: "Le Prophète ﷺ enseigne que la femme a sa propre nature qu'il faut respecter plutôt que chercher à changer. L'acceptation bienveillante est la clé d'une relation durable.",
    explicacionEN: "The Prophet ﷺ teaches that woman has her own nature that must be respected rather than sought to change. Benevolent acceptance is the key to a lasting relationship.",
    emoji: '❤️',
  },
  {
    id: 'had3',
    texte: "Offrez-vous des cadeaux, vous vous aimerez davantage.",
    texteEN: "Give gifts to one another, for you will love each other more.",
    source: "Al-Adab Al-Mufrad - Hassan",
    explication: "Le cadeau n'a pas besoin d'être coûteux. Un fruit, une fleur, un mot écrit... Ce qui compte, c'est l'intention et l'attention portée à l'autre.",
    explicacionEN: "The gift does not need to be costly. A fruit, a flower, a written word... What matters is the intention and the attention given to the other.",
    emoji: '🎁',
  },
  {
    id: 'had4',
    texte: "Ne haïssez pas une croyante (épouse). Si vous n'aimez pas une de ses qualités, vous en apprécierez une autre.",
    texteEN: "Do not hate a believing woman. If you dislike one of her qualities, you will appreciate another.",
    source: "Muslim",
    explication: "Le Prophète ﷺ nous invite à regarder l'ensemble de la personne, pas seulement ses défauts. L'amour mature accepte l'autre dans sa globalité.",
    explicacionEN: "The Prophet ﷺ invites us to look at the whole person, not just their faults. Mature love accepts the other in their wholeness.",
    emoji: '🌿',
  },
  {
    id: 'had5',
    texte: "Khadija me croyait quand tous me traitaient de menteur, elle m'aidait avec sa richesse quand on m'avait tout pris, et Allah m'a donné des enfants par elle.",
    texteEN: "Khadijah believed me when everyone called me a liar, she helped me with her wealth when everyone took everything from me, and Allah gave me children through her.",
    source: "Sahih al-Bukhari 3818",
    explication: "Le Prophète ﷺ évoquait Khadija avec une tendresse immense des années après sa mort. Son souvenir nous enseigne la fidélité, la reconnaissance et la force du soutien conjugal.",
    explicacionEN: "The Prophet ﷺ spoke of Khadijah with immense tenderness years after her death. Her memory teaches us faithfulness, gratitude, and the strength of marital support.",
    emoji: '💍',
  },
  {
    id: 'had6',
    texte: "Que chacun parmi vous soit bon envers sa femme. Si tu veux la redresser complètement tu la briseras, mais si tu la laisses elle restera tordue. Soyez bons envers les femmes.",
    texteEN: "Each of you should be good to your wife. If you wish to completely straighten her you will break her, but if you leave her she will remain bent. Be good to women.",
    source: "Bukhari",
    explication: "Ce hadith revient plusieurs fois dans la Sunnah, soulignant son importance capitale. L'homme est invité à la douceur et à l'acceptation plutôt qu'à vouloir tout contrôler.",
    explicacionEN: "This hadith appears several times in the Sunnah, highlighting its critical importance. Men are invited to gentleness and acceptance rather than seeking to control everything.",
    emoji: '🌿',
  },
  {
    id: 'had7',
    texte: "Le fort n'est pas celui qui terrasse les autres ; le fort est celui qui se maîtrise dans la colère.",
    texteEN: "The strong is not the one who overcomes others; the strong is the one who controls himself in anger.",
    source: "Sahih al-Bukhari 6114",
    explication: "La vraie force dans un couple, c'est la maîtrise de soi. Protéger son conjoint de sa propre colère est un acte de courage et d'amour.",
    explicacionEN: "True strength in a couple is self-control. Protecting your spouse from your own anger is an act of courage and love.",
    emoji: '💪',
  },
  {
    id: 'had8',
    texte: "Votre épouse a des droits sur vous.",
    texteEN: "Your wife has rights over you.",
    source: "Abu Dawud",
    explication: "Le mariage n'est pas une possession mais un contrat de responsabilités mutuelles. Prendre conscience des droits de son conjoint est le premier pas vers une relation équilibrée.",
    explicacionEN: "Marriage is not ownership but a contract of mutual responsibilities. Becoming aware of your spouse's rights is the first step toward a balanced relationship.",
    emoji: '⚖️',
  },
  {
    id: 'had9',
    texte: "Lorsqu'un homme aime son frère, qu'il l'informe qu'il l'aime.",
    texteEN: "When a man loves his brother, he should tell him that he loves him.",
    source: "Sunan Abi Dawud 5124",
    explication: "Exprimer verbalement son amour à son conjoint(e) renforce le lien affectif. Le Prophète ﷺ recommandait de dire à ceux qu'on aime qu'on les aime — un acte simple qui transforme la relation.",
    explicacionEN: "Verbally expressing love for one's spouse strengthens emotional bonds. The Prophet ﷺ recommended telling those we love that we love them — a simple act that transforms relationships.",
    emoji: '💝',
  },
  {
    id: 'had10',
    texte: "Que chacun de vous prenne soin de son épouse, car elle est un dépôt (amanah) confié entre vos mains.",
    texteEN: "Each of you should take care of his wife, for she is a trust (amanah) placed in your hands.",
    source: "Ibn Majah",
    explication: "L'épouse n'est pas une propriété mais un dépôt (amanah) sacré. Cette responsabilité doit inspirer la douceur, la protection et le respect au quotidien.",
    explicacionEN: "A wife is not property but a sacred trust (amanah). This responsibility should inspire gentleness, protection, and daily respect.",
    emoji: '🤲',
  },
  {
    id: 'had11',
    texte: "La femme est un dépôt (amanah) confié au mari. Il lui est interdit de la maltraiter.",
    texteEN: "The woman is a trust (amanah) entrusted to the husband. He is forbidden from mistreating her.",
    source: "Tirmidhi",
    explication: "L'Islam interdit explicitement tout mauvais traitement. Le foyer doit être un lieu de paix, de sécurité et de bienveillance pour chaque époux.",
    explicacionEN: "Islam explicitly prohibits all mistreatment. The home must be a place of peace, security, and kindness for every spouse.",
    emoji: '🛡️',
  },
  {
    id: 'had12',
    texte: "Les femmes sont les sœurs jumelles des hommes.",
    texteEN: "Women are the twin halves of men.",
    source: "Sunan Abi Dawud 236",
    explication: "L'Islam reconnaît la parité fondamentale entre époux dans leurs droits et obligations. Cette égalité est le fondement d'une relation juste et équilibrée.",
    explicacionEN: "Islam recognizes the fundamental equality between spouses in their rights and obligations. This equality is the foundation of a just and balanced relationship.",
    emoji: '🔄',
  },
  {
    id: 'had13',
    texte: "Le croyant ne doit pas haïr la croyante. S'il n'aime pas un de ses traits, il en trouvera un autre qu'il aimera.",
    texteEN: "The believer must not hate the believing woman. If he dislikes one of her traits, he will find another that he will love.",
    source: "Muslim",
    explication: "Personne n'est parfait. La sagesse conjugale consiste à focaliser son regard sur les qualités de l'autre plutôt que sur ses manques.",
    explicacionEN: "No one is perfect. Marital wisdom consists of focusing one's gaze on the other's qualities rather than their shortcomings.",
    emoji: '🌸',
  },
  {
    id: 'had14',
    texte: "Qu'Allah fasse miséricorde à l'homme qui se lève la nuit pour prier et réveille sa femme, et à la femme qui se lève pour prier et réveille son mari.",
    texteEN: "May Allah have mercy on the man who gets up at night to pray and wakes his wife, and on the woman who gets up to pray and wakes her husband.",
    source: "Abu Dawud",
    explication: "La prière nocturne partagée est l'un des plus beaux actes d'amour spirituel entre époux. Elle crée une intimité avec Allah et entre eux.",
    explicacionEN: "The shared night prayer is one of the most beautiful acts of spiritual love between spouses. It creates intimacy with Allah and between them.",
    emoji: '🌙',
  },
  {
    id: 'had15',
    texte: "La meilleure d'entre vous est celle qui, lorsque tu la regardes, te réjouit, lorsque tu lui ordonnes quelque chose de licite, elle t'obéit, et qui préserve ton honneur en ton absence.",
    texteEN: "The best of you is the one who, when you look at her, brings you joy; when you command her something lawful, she obeys; and who guards your honor in your absence.",
    source: "Sunan an-Nasa'i 3231",
    explication: "Ce hadith décrit trois piliers de la vie conjugale : la joie mutuelle, la coopération dans le bien, et la fidélité. Des qualités précieuses à cultiver pour les deux époux.",
    explicacionEN: "This hadith describes three pillars of married life: mutual joy, cooperation in good, and faithfulness — precious qualities to cultivate for both spouses.",
    emoji: '✨',
  },
  {
    id: 'had16',
    texte: "Aucun croyant ne doit garder de la rancœur envers une croyante. S'il lui en veut pour une chose, il sera satisfait d'une autre.",
    texteEN: "No believer should hold resentment toward a believing woman. If he is upset with her about one thing, he will be satisfied about another.",
    source: "Muslim",
    explication: "La rancœur accumulée est l'ennemi silencieux des couples. Ce hadith nous invite à ne pas laisser les griefs s'installer et à chercher activement ce qui nous unit.",
    explicacionEN: "Accumulated resentment is the silent enemy of couples. This hadith invites us not to let grievances settle and to actively seek what unites us.",
    emoji: '🕊️',
  },
  {
    id: 'had17',
    texte: "Ce que tu dépenses pour ta famille est une sadaqa, jusqu'à la bouchée que tu portes à la bouche de ton épouse.",
    texteEN: "What you spend for your family is a sadaqa, even the morsel you place in your wife's mouth.",
    source: "Sahih al-Bukhari 5351",
    explication: "Chaque geste de générosité envers son foyer est un acte d'adoration. Nourrir sa famille, subvenir à ses besoins — tout cela compte auprès d'Allah.",
    explicacionEN: "Every act of generosity toward one's household is an act of worship. Providing for one's family and attending to its needs — all of this counts with Allah.",
    emoji: '💰',
  },
  {
    id: 'had18',
    texte: "Prenez soin des femmes, car elles ont été créées d'une côte. Ce qu'il y a de plus courbé dans la côte c'est le sommet. Si tu cherches à le redresser tu le casseras, et si tu le laisses, il restera courbé. Prenez soin des femmes.",
    texteEN: "Take care of women, for they were created from a rib. The most curved part of the rib is the top. If you try to straighten it you will break it, and if you leave it, it will remain curved. Take care of women.",
    source: "Bukhari & Muslim",
    explication: "Ce hadith poétique invite l'homme à la sagesse et à l'acceptation. Vouloir tout contrôler ou 'corriger' son épouse mène à la rupture. La bienveillance et la flexibilité préservent le lien.",
    explicacionEN: "This poetic hadith invites wisdom and acceptance. Wanting to control or 'correct' your wife leads to breakage. Kindness and flexibility preserve the bond.",
    emoji: '🌱',
  },
  {
    id: 'had19',
    texte: "Le divorce est la chose licite la plus détestée aux yeux d'Allah.",
    texteEN: "Divorce is the most detestable of lawful things in the sight of Allah.",
    source: "Sunan Abi Dawud 2178",
    explication: "Ce hadith rappelle que le mariage mérite d'être préservé avec effort et patience. Avant d'envisager la séparation, tout faire pour reconstruire est la voie la plus noble.",
    explicacionEN: "This hadith reminds us that marriage deserves to be preserved with effort and patience. Before considering separation, doing everything to rebuild is the most noble path.",
    emoji: '🔗',
  },
  {
    id: 'had20',
    texte: "Parmi les droits de l'épouse sur son mari : qu'il la nourrisse quand il mange, qu'il la vête quand il se vêt, qu'il ne frappe pas son visage et qu'il ne l'abandonne que dans la maison.",
    texteEN: "Among the wife's rights over her husband: that he feed her when he eats, clothe her when he clothes himself, not strike her face, and not shun her except in the home.",
    source: "Ibn Majah - Hassan",
    explication: "Ces droits concrets montrent l'attention de l'Islam pour la dignité de la femme. Chaque obligation est un appel quotidien à la présence, au soin et au respect.",
    explicacionEN: "These concrete rights show Islam's attention to women's dignity. Each obligation is a daily call to presence, care, and respect.",
    emoji: '💎',
  },
  {
    id: 'had21',
    texte: "Le croyant qui a la foi la plus parfaite est celui qui a le meilleur caractère, et le meilleur d'entre vous est celui qui est le meilleur envers sa femme.",
    texteEN: "The believer with the most perfect faith is the one with the best character, and the best of you is the one who is best to his wife.",
    source: "Jami` at-Tirmidhi 1162",
    explication: "Ce hadith lie la perfection de la foi au bon caractère dans le couple. Travailler sur son comportement envers son épouse, c'est travailler sur sa foi.",
    explicacionEN: "This hadith links perfection of faith to good character within the couple. Working on one's behavior toward one's spouse is working on one's faith.",
    emoji: '🤲',
  },
  {
    id: 'had22',
    texte: "Vous avez des droits sur vos épouses et elles ont des droits sur vous.",
    texteEN: "You have rights over your wives and they have rights over you.",
    source: "Tirmidhi",
    explication: "Le mariage islamique n'est pas une relation de domination mais un équilibre de droits et de responsabilités. La conscience de ce double devoir est le fondement d'une relation juste.",
    explicacionEN: "Islamic marriage is not a relationship of domination but a balance of rights and responsibilities. Awareness of this double duty is the foundation of a just relationship.",
    emoji: '⚖️',
  },
  {
    id: 'had23',
    texte: "Certes Allah est doux et Il aime la douceur en toute chose.",
    texteEN: "Indeed Allah is gentle and He loves gentleness in all things.",
    source: "Sahih Muslim 2593",
    explication: "La douceur n'est pas une faiblesse — c'est un attribut d'Allah Lui-même. Dans le couple, la douceur dans la parole et le geste est un chemin vers Sa satisfaction.",
    explicacionEN: "Gentleness is not weakness — it is an attribute of Allah Himself. In the couple, gentleness in word and gesture is a path toward His satisfaction.",
    emoji: '🌷',
  },
  {
    id: 'had24',
    texte: "Parmi les droits de l'épouse sur son mari : la nourrir quand il mange, la vêtir quand il se vêt, ne pas frapper son visage, ne pas la laidir, et ne pas s'éloigner d'elle sauf dans la maison.",
    texteEN: "Among the wife's rights over her husband: to feed her when he eats, clothe her when he clothes himself, not strike her face, not humiliate her, and not stay away from her except in the home.",
    source: "Abu Dawud",
    explication: "Ces droits concrets révèlent l'attention de l'Islam pour la dignité de la femme. Chaque droit est un appel à la présence, au soin et au respect quotidien.",
    explicacionEN: "These concrete rights reveal Islam's attention to women's dignity. Each right is a call to daily presence, care, and respect.",
    emoji: '🏡',
  },
  {
    id: 'had25',
    texte: "Celui qui ne remercie pas les gens ne remercie pas Allah.",
    texteEN: "Whoever does not thank people does not thank Allah.",
    source: "Abu Dawud - Sahih",
    explication: "La gratitude envers son conjoint est une forme de gratitude envers Allah. Exprimer 'merci' sincèrement à son époux ou son épouse est un acte spirituel.",
    explicacionEN: "Gratitude toward one's spouse is a form of gratitude toward Allah. Expressing 'thank you' sincerely to your husband or wife is a spiritual act.",
    emoji: '🙏',
  },
  {
    id: 'had26',
    texte: "Allah éprouve de la jalousie [protectrice] et le croyant éprouve de la jalousie. La jalousie d'Allah, c'est qu'il n'aime pas que le croyant fasse ce qu'il a interdit.",
    texteEN: "Allah is jealous [protective] and the believer is jealous. Allah's jealousy is that the believer does what He has forbidden.",
    source: "Sahih al-Bukhari 5223",
    explication: "La 'ghirah' islamique est la protection saine de son conjoint et de la sainteté du mariage. Elle se distingue de la jalousie destructive (hasad) qui est interdite. Une vigilance bienveillante préserve le foyer.",
    explicacionEN: "Islamic 'ghirah' is the healthy protection of one's spouse and the sanctity of marriage. It is distinct from destructive jealousy (hasad) which is forbidden. Mindful watchfulness preserves the home.",
    emoji: '🔥',
  },
  {
    id: 'had27',
    texte: "Faites-vous des cadeaux mutuellement, cela engendre l'amour entre vous et fait disparaître la rancœur.",
    texteEN: "Give gifts to one another; it generates love between you and removes resentment.",
    source: "Al-Adab Al-Mufrad",
    explication: "Le cadeau a un double effet : il crée de l'amour et dissout les tensions accumulées. Une petite attention régulière entretient la flamme mieux que les grandes déclarations rares.",
    explicacionEN: "The gift has a dual effect: it creates love and dissolves accumulated tensions. A small regular gesture maintains the flame better than rare grand declarations.",
    emoji: '🎀',
  },
  {
    id: 'had28',
    texte: "Les âmes sont des armées rassemblées. Celles qui se connaissent s'allient, et celles qui ne se connaissent pas se séparent.",
    texteEN: "Souls are like conscripted soldiers; those who are alike come together, and those who are different part ways.",
    source: "Sahih al-Bukhari 3336",
    explication: "Le mariage réunit deux âmes qui se reconnaissent. Cette compatibilité des âmes est un don d'Allah — elle mérite d'être cultivée par la connaissance mutuelle et le temps partagé.",
    explicacionEN: "Marriage unites two souls that recognize each other. This soul compatibility is a gift from Allah — it deserves to be cultivated through mutual knowledge and shared time.",
    emoji: '🌌',
  },
  {
    id: 'had29',
    texte: "Lorsque l'un de vous aime son frère — ou sa sœur — qu'il lui fasse savoir.",
    texteEN: "When one of you loves his brother — or his sister — let him tell them.",
    source: "Tirmidhi - Sahih",
    explication: "Ce hadith s'applique pleinement au couple. Dire 'je t'aime' sincèrement et régulièrement à son conjoint est une sunnah. Ne pas laisser l'amour implicite — l'exprimer.",
    explicacionEN: "This hadith applies fully to the couple. Sincerely and regularly saying 'I love you' to your spouse is a sunnah. Don't leave love implicit — express it.",
    emoji: '💬',
  },
  {
    id: 'had30',
    texte: "Le mariage fait partie de ma sunnah. Celui qui ne suit pas ma sunnah n'est pas des miens.",
    texteEN: "Marriage is part of my sunnah. Whoever does not follow my sunnah is not of me.",
    source: "Ibn Majah - Sahih",
    explication: "Le mariage n'est pas seulement une institution sociale — c'est une sunnah du Prophète ﷺ. S'investir dans son mariage, le chérir et le faire prospérer est suivre son exemple.",
    explicacionEN: "Marriage is not just a social institution — it is a sunnah of the Prophet ﷺ. Investing in one's marriage, cherishing it, and making it flourish is following his example.",
    emoji: '🕌',
  },
];

// ─── DÉFIS HEBDOMADAIRES ─────────────────────────────────────────────────────
export const DEFIS = [
  {
    id: 'd1',
    titre: "La semaine de la gratitude",
    titreEN: "Gratitude Week",
    description: "Chaque jour cette semaine, exprimez un remerciement sincère à votre conjoint(e) pour quelque chose de spécifique.",
    descriptionEN: "Each day this week, express a sincere thank-you to your spouse for something specific.",
    duree: "7 jours",
    difficulte: "Facile",
    emoji: '🙏',
    jours: [
      "Dis merci pour une chose concrète qu'il/elle a faite cette semaine.",
      "Écris-lui un message de remerciement inattendu.",
      "Remercie-le/la devant un proche ou un ami.",
      "Dis-lui ce que tu apprécies dans sa personnalité.",
      "Remercie-le/la pour quelque chose qu'il/elle fait et que tu tiens pour acquis.",
      "Prépare-lui quelque chose qu'il/elle aime pour exprimer ta gratitude.",
      "Faites ensemble un dua de gratitude pour votre union.",
    ],
    joursEN: [
      "Say thank you for one concrete thing they did this week.",
      "Send them an unexpected message of appreciation.",
      "Thank them in front of a friend or family member.",
      "Tell them what you appreciate about their personality.",
      "Thank them for something they do that you take for granted.",
      "Prepare something they love to express your gratitude.",
      "Make a dua of gratitude together for your union.",
    ],
  },
  {
    id: 'd2',
    titre: "La semaine sans écrans",
    titreEN: "Screen-Free Week",
    description: "Réservez 1h par soir sans téléphone pour vous retrouver vraiment.",
    descriptionEN: "Set aside 1 hour each evening without phones to truly reconnect.",
    duree: "7 jours",
    difficulte: "Moyen",
    emoji: '📵',
    jours: [
      "Dînez ensemble sans téléphone ni TV ce soir.",
      "Faites une promenade de 30 minutes ensemble.",
      "Jouez à un jeu de société ou lisez ensemble.",
      "Partagez 3 souvenirs heureux de votre couple.",
      "Préparez un repas ensemble sans distraction.",
      "Regardez les étoiles ou contemplez la nature ensemble.",
      "Faites une prière de nuit ensemble et partagez vos espoirs.",
    ],
    joursEN: [
      "Have dinner together tonight with no phone or TV.",
      "Take a 30-minute walk together.",
      "Play a board game or read together.",
      "Share 3 happy memories from your relationship.",
      "Prepare a meal together without any distraction.",
      "Watch the stars or enjoy nature together.",
      "Pray together at night and share your hopes.",
    ],
  },
  {
    id: 'd3',
    titre: "Défi communication bienveillante",
    titreEN: "Compassionate Communication Challenge",
    description: "Cette semaine, remplacez toute critique par une demande positive.",
    descriptionEN: "This week, replace every criticism with a positive request.",
    duree: "7 jours",
    difficulte: "Difficile",
    emoji: '💬',
    jours: [
      "Identifiez une critique récurrente que vous faites. Comment la transformer en demande ?",
      "Aujourd'hui, zéro reproche. Exprimez uniquement des besoins.",
      "Pratiquez l'écoute active : écoutez sans préparer votre réponse.",
      "Exprimez un désaccord en commençant par 'Je comprends que tu...'",
      "Faites-vous un retour positif sur comment vous communiquez ce semaine.",
      "Parlez d'un sujet difficile avec la méthode : ressenti + besoin + demande.",
      "Évaluez ensemble : qu'est-ce qui a changé cette semaine dans vos échanges ?",
    ],
    joursEN: [
      "Identify one recurring criticism you make. How can you turn it into a request?",
      "Today, zero complaints. Express only needs.",
      "Practice active listening: listen without preparing your response.",
      "Express a disagreement starting with 'I understand that you...'",
      "Give each other positive feedback on how you've been communicating this week.",
      "Discuss a difficult topic using: feeling + need + request.",
      "Evaluate together: what changed in your communication this week?",
    ],
  },
  {
    id: 'd4',
    titre: "Les 5 langages de l'amour",
    titreEN: "The 5 Love Languages",
    description: "Découvrez et pratiquez les 5 façons d'exprimer l'amour.",
    descriptionEN: "Discover and practice the 5 ways to express love.",
    duree: "5 jours",
    difficulte: "Facile",
    emoji: '❤️',
    jours: [
      "Jour 1 - Paroles : Dites 3 choses que vous appréciez vraiment chez votre conjoint(e).",
      "Jour 2 - Temps : Passez 1h ensemble sans objectif, juste pour être ensemble.",
      "Jour 3 - Cadeaux : Offrez quelque chose, même symbolique, qui lui fera plaisir.",
      "Jour 4 - Services : Faites quelque chose pour lui/elle sans qu'on vous le demande.",
      "Jour 5 - Toucher : Tenez-vous la main, faites un câlin prolongé ce soir.",
    ],
    joursEN: [
      "Day 1 - Words: Say 3 things you truly appreciate about your spouse.",
      "Day 2 - Time: Spend 1 hour together with no agenda, just being together.",
      "Day 3 - Gifts: Offer something, even symbolic, that will bring them joy.",
      "Day 4 - Acts: Do something for them without being asked.",
      "Day 5 - Touch: Hold hands, share a long hug this evening.",
    ],
  },
];
