// Nouveaux défis à ajouter à data.js
export const NOUVEAUX_DEFIS = [
  {
    id: 'd5',
    titre: "Défi Ramadan en couple",
    description: "Faites de ce Ramadan le plus spirituel de votre vie conjugale.",
    duree: "7 jours",
    difficulte: "Moyen",
    emoji: '🌙',
    jours: [
      "Levez-vous ensemble pour le suhour et faites une courte prière.",
      "Lisez ensemble un verset du Coran avec son explication.",
      "Rompez le jeûne ensemble sans télévision ni téléphone.",
      "Priez ensemble tarawih à la maison ce soir.",
      "Partagez chaque soir une chose que vous avez apprise spirituellement.",
      "Faites ensemble une liste de dua pour votre famille et votre avenir.",
      "Passez la nuit ensemble à prier et à faire du dhikr. Cherchez le Qadr ensemble.",
    ],
  },
  {
    id: 'd6',
    titre: "Défi de l'intimité émotionnelle",
    description: "Redécouvrez-vous l'un l'autre profondément.",
    duree: "5 jours",
    difficulte: "Moyen",
    emoji: '💞',
    jours: [
      "Partagez chacun votre plus grande peur. Écoutez sans jugement.",
      "Racontez-vous votre plus beau souvenir ensemble. Revivez-le.",
      "Dites-vous mutuellement 3 rêves que vous n'avez jamais osé partager.",
      "Parlez de votre enfance. Ce qui vous a construit. Ce que vous voulez transmettre.",
      "Répondez ensemble : 'Dans 10 ans, je veux qu'on soit...' Construisez la réponse ensemble.",
    ],
  },
  {
    id: 'd7',
    titre: "Défi belle-famille sereine",
    description: "Établissez des bases saines avec vos familles respectives.",
    duree: "7 jours",
    difficulte: "Difficile",
    emoji: '🏡',
    jours: [
      "Discutez ensemble : quelles sont les limites saines avec nos familles ?",
      "Chacun appelle SA famille pour prendre des nouvelles. Aucune interférence.",
      "Faites la liste des tensions liées à la belle-famille. Priorisez-les ensemble.",
      "Pour chaque tension identifiée : décidez ensemble d'une réponse commune.",
      "Appliquez une limite que vous avez décidée ensemble. Faites-le avec respect.",
      "Remerciez vos familles pour ce qu'elles vous ont apporté.",
      "Évaluez : comment s'est passée cette semaine ? Qu'est-ce qui a changé ?",
    ],
  },
  {
    id: 'd8',
    titre: "Défi finances transparentes",
    description: "Mettez les cartes sur table et construisez ensemble.",
    duree: "5 jours",
    difficulte: "Difficile",
    emoji: '💰',
    jours: [
      "Partagez honnêtement vos revenus et dépenses actuels. Sans jugement.",
      "Identifiez ensemble 3 objectifs financiers communs (ex: Oumra, épargne, achat).",
      "Définissez qui paie quoi. Clarté = paix.",
      "Identifiez les dépenses qui créent des tensions. Proposez des solutions.",
      "Faites dua ensemble pour la barakah dans vos revenus et votre foyer.",
    ],
  },
  {
    id: 'd9',
    titre: "Défi de la réconciliation",
    description: "Guérissez les blessures passées et repartez sur de nouvelles bases.",
    duree: "7 jours",
    difficulte: "Difficile",
    emoji: '🕊️',
    jours: [
      "Chacun écrit les 3 blessures passées qu'il n'a pas encore vraiment pardonnées.",
      "Chacun demande pardon pour SA part de responsabilité dans les conflits passés.",
      "Définissez ensemble 3 règles pour éviter de retomber dans les mêmes schémas.",
      "Faites une prière commune de 2 rakats pour demander à Allah de purifier votre relation.",
      "Brûlez (ou déchirez) symboliquement vos listes de blessures. Tournez la page.",
      "Passez une journée sans évoquer le passé. Vivez seulement dans le présent.",
      "Rédigez ensemble votre 'nouveau départ' : comment vous voulez être à partir d'aujourd'hui.",
    ],
  },
  {
    id: 'd10',
    titre: "Défi spiritualité partagée",
    description: "Faites d'Allah le centre de votre foyer.",
    duree: "7 jours",
    difficulte: "Facile",
    emoji: '🤲',
    jours: [
      "Priez ensemble au moins une prière par jour cette semaine.",
      "Lisez ensemble le tafsir d'un verset sur le mariage.",
      "Faites du dhikr ensemble pendant 10 minutes avant de dormir.",
      "Donnez la sadaqa ensemble — même 1€. Discutez de qui vous voulez aider.",
      "Apprenez ensemble un dua pour le couple et récitez-le ensemble.",
      "Parlez de ce que vous voulez construire spirituellement comme famille.",
      "Terminez la semaine par une longue dua commune. Dites à Allah tout ce que vous souhaitez pour votre couple.",
    ],
  },
];
